// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HQfieqcdTvB045vQ-2SWG4CDWl-VE98',
    appId: '1:836852884281:web:f7b26c4dd4df23fa35bee8',
    messagingSenderId: '836852884281',
    projectId: 'my-firestore-test3684',
    authDomain: 'my-firestore-test3684.firebaseapp.com',
    storageBucket: 'my-firestore-test3684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHC0ivisqO80_1r1qDC7LKqsq96_Yw9Dc',
    appId: '1:836852884281:android:4921bcce138d9f4a35bee8',
    messagingSenderId: '836852884281',
    projectId: 'my-firestore-test3684',
    storageBucket: 'my-firestore-test3684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGbjhOHQjK3JFyrd2hzhrKXWp34RH2_k',
    appId: '1:836852884281:ios:42660de67babbe6735bee8',
    messagingSenderId: '836852884281',
    projectId: 'my-firestore-test3684',
    storageBucket: 'my-firestore-test3684.appspot.com',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGbjhOHQjK3JFyrd2hzhrKXWp34RH2_k',
    appId: '1:836852884281:ios:c497b219c9ccd39835bee8',
    messagingSenderId: '836852884281',
    projectId: 'my-firestore-test3684',
    storageBucket: 'my-firestore-test3684.appspot.com',
    iosBundleId: 'com.example.untitled7.RunnerTests',
  );
}
